apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: payment-gateway
  name: payment-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: payment-gateway
    spec:
      containers:
      - image: acrdockerdemomtc.azurecr.io/payment-gateway
        name: payment-gateway
        resources: {}
      restartPolicy: Always
      imagePullSecrets:
        - name: demo_mtc_secret
status: {}
